### ISSUE TITLE
CountDownTimer interval

### ISSUE THREAD

**Issue by P1tr0w** [MatoPlus/Orgmodoro#1]
Just saw that the interval (COUNTDOWN_INTERVAL) is set at 50ms, a really low value. As per android documentation: 

> The calls to onTick(long) are synchronized to this object so that one call to onTick(long) won't ever occur before the previous callback is complete. This is only relevant when the implementation of onTick(long) takes an amount of time to execute that is significant compared to the countdown interval.

So maybe the timer's inaccuracy stems from the low interval? Gotta check it myself, but couldn't yet develop a test for this case.

**Comment by MatoPlus** [comment]
First, I want to point out that the interval value is low in order to smooth how the progress bar transitions (The progress bar updates on tick). Because of this, I prefer the interval value to be somewhere around 50-200ms

I also did do some testing via logging.  So tested with interval countdowns of 1000ms, 100ms, and then 1ms.  The countdown starts at 60000ms

With 1000ms countdown interval:
![1000](https://user-images.githubusercontent.com/44826218/60847068-72453e00-a1af-11e9-9036-168721a45c12.png)

With 100ms countdown interval:
![100](https://user-images.githubusercontent.com/44826218/60847134-9ef95580-a1af-11e9-84bd-302e5a3dade0.png)

With 1ms: countdown interval
![1](https://user-images.githubusercontent.com/44826218/60847139-a7ea2700-a1af-11e9-8c77-b72fbc8a88b7.png)

From above, you can see that all cases result in loss of accuracy. But you say that the 1000ms case loses accuracy "the least amount of times" throughout the duration of 60000ms. But I think a longer interval feels off. Let's say there is a case when the time displayed is wrong, it takes 1000ms for the timer to readjust vs 100ms to adjust. If the time is correctly adjusted within 500ms, the 100ms interval would be much preferred. For this problem, I think there is a sweet spot for the interval value. I'll try to do some continued testing with 60min timers and get a better value.

**Comment by MatoPlus** [comment]
For now, I'm going to say that a countdown interval of 150ms is accurate enough for a timer. I'm closing this issue for now. Feel free to open a new issue if anything arises.
